### ISSUE TITLE
black stripe(s) separating the toolbar from the rest of the app

### ISSUE THREAD

**Issue by theenduser** [fossfreedom/alternative-toolbar#11]
I'm wondering if sth can be done about that black stripe, separating the toolbar from the rest of the app? I've noticed that it's not there with the old (not gnome-shell) plugin and that it is there without the plugin. I hope you get what I mean.

**Comment by fossfreedom** [comment]
please can you add a screenshot with an arrow pointing at what you are seeing.

What GTK version are you using?  What distro and desktop version are you using?

Thanks.

**Comment by theenduser** [comment]
![screenshot from 2015-03-24 17 03 23](https://cloud.githubusercontent.com/assets/1701311/6831435/8fb40780-d320-11e4-9210-c79ddaab036e.png)

I'm not too handy with drawing arrows and such. I'm using Ozon (Fedora 21), GNOME 3.14.

**Comment by fossfreedom** [comment]
![pic](http://i.imgur.com/IwcXqzo.png)

I think that is due to the GTK shadow-in effect of the window.

The forthcoming rhythmbox 3.2 (not yet released) has tidied this up - many/all of the shadow-in effects have been removed to become flat style windows as per the picture i.e. I'm using the latest upstream source to show you that picture.

Possibly it may be possible to change this in rhythmbox 3.02 to 3.1.  I'll leave this open for the moment.

Happy to receive any fixes ...

**Comment by theenduser** [comment]
Just to be sure: I'm talking about those two lines on the bottom. So I'm not sure why you're showing me a  screenshot of the top part. That part's OK. :)

I have no technical knowledge whatsoever btw.

**Comment by fossfreedom** [comment]
the CSD - client side decoration - is the top part of the screen.  Hence why I assume you titled the question...

anyway...

![pic](http://i.imgur.com/1eyCUJA.png)

bottom part of the screen ( on the refactor branch ) - better?

**Comment by theenduser** [comment]
Pardon my ignorance. I edited the issue. Let's hope the new version will fix this indeed. Thnx for looking into it! :)
