### ISSUE TITLE
Papercut - Sidebar needs border on the right.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#21]
Because if it doesn't have one and when search is toggled, the area where the search bar and the sidebar meet looks funny.
![screenshot from 2015-04-06 13 38 34](https://cloud.githubusercontent.com/assets/1658870/7003395/702b44fa-dc62-11e4-8a37-e20be680accf.png)

**Comment by fossfreedom** [comment]
![pic](http://orig01.deviantart.net/6dfd/f/2015/111/e/c/new_look_of_rhythmbox_by_chantrongchien1977-d8qm9xi.png)

Interesting - just saw this on deviantart - the theme does affect how the various elements interact - in this picture/theme there is a definitive border between the sidebar and search toggle.

**Comment by me4oslav** [comment]
Hmm, @satya164 (Satya is Numix and Ozon guy and he wrote the code for the GTK theme) - can we get some info on this issue?

**Comment by satya164** [comment]
The theme does affect the styling. But it's not a good idea to add a border to all sidebars with the theme. If we do, the sidebars which are GtkPaned or sidebars with frames will result in double border.

**Comment by me4oslav** [comment]
So, best way to fix thi

**Comment by fossfreedom** [comment]
Looking at this commit for Rhythmbox 3.2

 - https://github.com/GNOME/rhythmbox/commit/67579a26d5272c2838b82da61aada8ecc34726da

The Gtk Paned CSS has been changed to one pixel wide - so that's probably why Rhythmbox 3.2 sees a clear border and the main tracking listing.

When you get time, please upgrade to Rhythmbox 3.2 and see how these CSS styling changes that upstream has done affects what you are seeing with your theme.

**Comment by me4oslav** [comment]
We can close this bug now.
