### ISSUE TITLE
[FEATURE REQUEST] Graphic setup.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#45]
Wireframe:
![screenshot from 2015-05-11 18 42 38](https://cloud.githubusercontent.com/assets/1658870/7568811/9e009f1c-f80d-11e4-83e2-ee43d7b56574.png)

The wireframe from above is pretty self explaining and sand the updates it should not be that hard to implement.
My idea about the updates is that it will only offer an update when there is version bump on github in the master branch. Of course this installer will only be for people that have grabbed the plugin from github and updates will also be handled by fetching from Githhub.
Updating is not a be all end all feature that must be implemented in the setup at all cost and can be delayed for later on or not be implemented at all. It would be to have it, but it is not really mandatory.
This design can be used for all your other plugins too.
##

**Comment by benjaoming** [comment]
Hi @me4oslav 

I was wondering with this mockup if you are aware that this toolbar is often installed via PPA and .deb (for Ubuntu / Debian based distros) ? Because the very big work it would take to distribute software safely through your own installation mechanism would not really pay off since many (most?) users will install software through traditional channels like PPAs. This is more secure and gives you updates more frequently.

I'm not saying that downloading updates from a Github repo is insecure... more that the general practice of installing stuff directly from Github is insecure because anyone can clone a repo and give instructions for people to install whatever's in that repo.

Btw. these are not bad mockups, they would just be a very horrible mess to implement from a software POV :)
