### ISSUE TITLE
Add right click menu to song button label

### ISSUE THREAD

**Issue by veluria** [fossfreedom/alternative-toolbar#83]
Would be be feasible? I'm talking about the right click menu that also appears when clicking on a song your list. Sometimes, I'm finding myself anywhere but near the current song that's playing. I'd be great to have the right click menu then to access options such as 'Browse this Album'.

**Comment by fossfreedom** [comment]
Hi thanks for raising the issue.

Can you mock up a screenshot or two showing what the issue is?  I'm not really following what you are trying to explain.

Many thanks in advance.

**Comment by veluria** [comment]
Well, basically something like this. Obviously I've opened the right click menu from within the table, but I'd be great to have the ability to open it from the control bar at the bottom. Thanks for taking your time. :)

![screenshot from 2016-02-16 15-51-08](https://cloud.githubusercontent.com/assets/1119538/13079605/54362d8a-d4c5-11e5-9617-9f94a72a9adf.png)

**Comment by fossfreedom** [comment]
ok thanks!

much clearer.

I'll have a think - I can't think of an immediate way to implement this.  I'll have a closer look when I get some free time.

**Comment by fossfreedom** [comment]
this signal might do the trick - https://lazka.github.io/pgi-docs/#RB-3.0/classes/EntryView.html#RB.EntryView.signals.show_popup

**Comment by fossfreedom** [comment]
ok,
  having had some time to think about this.

I'm doubtful this will work in practise.

Let me explain further.  Say you are playing a song from the library view.  Then you switch to the Play Queue.  What is the right-click "browse by album" supposed to do?

If you are playing and have filtered the list of songs by another browse by album or via a category - again it seems rather strange to have to reset the whole library view.

Right-click stuff on labels is most unusual - people will not realise there is a right click available.  Its inconsistent UI with other labels which don't have a right click.

Probably https://github.com/fossfreedom/alternative-toolbar/issues/54 would cover this.  Maybe have a couple of buttons on the popover which allows you to display just album tracks/artist tracks instead of the tracks before and after what is currently playing.

**Comment by veluria** [comment]
Yeah, you are probably right. #54 looks very nice though.
